name: Continuous Integration

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ 'master','main' ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Import Content Trust Key
        run: cd build/ && ./assemble_api.jar.sh && ./prepare_release.sh
        shell: bash

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true # optional (default = false)
