name: Verify and Test

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ 'master','main' ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and Test
        run: cd build/ && ./assemble_api.sh && ./run_all_tests.sh

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          
      - name: Send Slack Notification
        if: ${{ always() }}
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action ${{ github.workflow }} result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\nAction: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action `${{ github.workflow }}` result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\nAction: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
